language: python
python:
  - "3.5"

install: "pip install -r requirements.txt"
before_script:
  - pip install -r test_requirements.txt --use-mirrors

script: python manage.py test

after_success:
  - coveralls