language: python
python:
  - "3.5"

install: "pip install -r requirements.txt"
before_script:
  - pip install -r test_requirements.txt

script:
  - python manage.py test scoreboard
  - coverage run --source=scoreboard manage.py test scoreboard

after_success:
  - coveralls