# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:27
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time_minutes', models.PositiveIntegerField()),
                ('game_time_seconds', models.PositiveIntegerField()),
                ('player_number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('G', 'Goal'), ('P', 'Penalty'), ('T', 'Timeout')], max_length=1)),
            ],
            options={
                'ordering': ['game_time_minutes', 'game_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=3)),
                ('color', colorful.fields.RGBColorField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Event')),
                ('assist', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('scoreboard.event',),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Event')),
                ('penalty_type', models.CharField(choices=[('T30', 'Technical'), ('P1', 'Personal 1M'), ('P2', 'Personal 2M'), ('P3', 'Personal 3M'), ('EXP', 'Expulsion')], max_length=3)),
            ],
            bases=('scoreboard.event',),
        ),
        migrations.CreateModel(
            name='TimeOut',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Event')),
            ],
            bases=('scoreboard.event',),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scoreboard.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='visiting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scoreboard.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Team'),
        ),
    ]
