# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time_minutes', models.PositiveIntegerField()),
                ('game_time_seconds', models.PositiveIntegerField()),
                ('player_number', models.PositiveIntegerField()),
                ('assist', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Team')),
            ],
            options={
                'abstract': False,
                'ordering': ['game_time_minutes', 'game_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time_minutes', models.PositiveIntegerField()),
                ('game_time_seconds', models.PositiveIntegerField()),
                ('player_number', models.PositiveIntegerField()),
                ('penalty_type', models.CharField(choices=[('T30', 'Technical'), ('P1', 'Personal 1M'), ('P2', 'Personal 2M'), ('P3', 'Personal 3M'), ('EXP', 'Expulsion')], max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Team')),
            ],
            options={
                'abstract': False,
                'ordering': ['game_time_minutes', 'game_time_seconds'],
            },
        ),
    ]
