# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('T30', 'Technical'), ('P1', 'Personal 1M'), ('P2', 'Personal 2M'), ('P3', 'Personal 3M'), ('EXP', 'Expulsion')], max_length=3)),
            ],
        ),
    ]
