# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_goal_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('G', 'Goal'), ('P', 'Penalty'), ('T', 'Timeout')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='type',
            field=models.CharField(choices=[('G', 'Goal'), ('P', 'Penalty'), ('T', 'Timeout')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
