# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:03
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20170128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
